name: Firebase Continuous Deployment

on:
#  push:
#    branches: [ master ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: npm ci
      - run: npm run build-prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --token $FIREBASE_TOKEN --project $PROJECT_ID
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_10 }}
          PROJECT_PATH: firebase
          PROJECT_ID: owm-a10-fb